version: '3'
services:

  nginx:
    image: nginx
    links:
      - server
    ports:
      - "${MAIN_PORT:-9002}:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/nginx_cache"
      - "./static:/static:ro"
    restart: unless-stopped
  webapp:
    build: webapp
    volumes:
      - "./webapp:/webapp"
      - "./static:/webapp/dist"
      - "/webapp/node_modules"
      - "/webapp/v8-compile-cache-0"
    environment:
      - NODE_ENV
  server:
    build: server
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - "./server:/server:rw"
      - "/server/node_modules"
    restart: unless-stopped
    environment:
      - NODE_ENV
  mongo:
    image: mongo
    volumes:
      - "./persistence/mongo:/data/db"
    restart: unless-stopped
