version: '3'
services:

  nginx:
    image: nginx
    links:
      - back
    ports:
      - "${MAIN_PORT:-9002}:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/nginx_cache"
      - "./static:/static:ro"
    restart: unless-stopped
  webapp:
    build: webapp
    volumes:
      - "./webapp:/webapp"
      - "./static:/webapp/dist"
      - "/webapp/node_modules"
      - "/webapp/v8-compile-cache-0"
    environment:
      - NODE_ENV
  back:
    build: ./back
    command: python -m flask run --host=0.0.0.0
    volumes:
      - ./back/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - "./persistence/mongo:/data/db"
    restart: unless-stopped
    env_file:
      - .env.dev